#!/usr/bin/env python3
"""Generate Prometheus recording + alerting rules from slos.yaml.

Outputs (all overwritten):
  rules.yaml                 PrometheusRule, production windows
  rules-demo.yaml            PrometheusRule, compressed demo windows
  prometheus/rules.yaml      plain rule file (promtool check/test)
  prometheus/rules-demo.yaml plain rule file

Recording rules per SLI and window W (prefix `slo` or `slodemo`):
  <p>:objective:ratio{sli}                 the objective, for dashboards
  <p>:sli_error:ratio_rateW{sli}           1 - good/total
  <p>:burn_rate:rateW{sli}                 error ratio / (1 - objective)
  <p>:error_budget_remaining:ratio{sli}    1 - error ratio over the budget window / (1 - objective)
  <p>:cost_per_1k_requests:rateW{llm_slo_cost_model}
Alerts: LLM<Sli>BurnRatePage, LLM<Sli>BurnRateTicket (+Demo), LLMCostBudgetExceeded(Demo).
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
HEADER = "# GENERATED by slo/gen_rules.py from slo/slos.yaml. Do not edit; run `make slo-gen`.\n"


def substitute(expr: str, window: str, profile: dict) -> str:
    out = expr.replace("{window}", window)
    for key, value in profile.items():
        out = out.replace("{" + key + "}", str(value))
    return " ".join(out.split())


def build(spec: dict, mode: str) -> list[dict]:
    cfg = spec["modes"][mode]
    p = cfg["metric_prefix"]
    wmap: dict = cfg["window_map"]
    profile_name = spec["profile_default"]
    profile = spec["profiles"][profile_name]
    windows = [*cfg["recording_windows"], cfg["budget_window"]]
    demo = mode == "demo"
    suffix = "Demo" if demo else ""
    common_labels = {"slo_mode": mode, "slo_profile": profile_name}

    recording: list[dict] = []
    alerts: list[dict] = []
    for slo in spec["slos"]:
        name = slo["name"]
        objective = float(slo["objective"])
        budget = round(1 - objective, 6)
        labels = {"sli": name, **common_labels}
        recording.append(
            {"record": f"{p}:objective:ratio", "expr": f"{objective:g}", "labels": labels}
        )
        for w in windows:
            good = substitute(slo["sli"]["good"], w, profile)
            total = substitute(slo["sli"]["total"], w, profile)
            recording.append(
                {
                    "record": f"{p}:sli_error:ratio_rate{w}",
                    "expr": f"clamp_min(1 - ({good}) / ({total}), 0)",
                    "labels": labels,
                }
            )
            recording.append(
                {
                    "record": f"{p}:burn_rate:rate{w}",
                    "expr": f'{p}:sli_error:ratio_rate{w}{{sli="{name}"}} / {budget:g}',
                    "labels": labels,
                }
            )
        bw = cfg["budget_window"]
        recording.append(
            {
                "record": f"{p}:error_budget_remaining:ratio",
                "expr": f'1 - {p}:sli_error:ratio_rate{bw}{{sli="{name}"}} / {budget:g}',
                "labels": labels,
            }
        )

        rates = slo.get("burn_rates", spec["burn_rates"])
        for severity in ("page", "ticket"):
            clauses = []
            pairs = []
            for pair in rates[severity]:
                long_w = wmap.get(pair["long"], pair["long"])
                short_w = wmap.get(pair["short"], pair["short"])
                f = pair["factor"]
                clauses.append(
                    f'({p}:burn_rate:rate{long_w}{{sli="{name}"}} > {f:g} '
                    f'and {p}:burn_rate:rate{short_w}{{sli="{name}"}} > {f:g})'
                )
                pairs.append(f"{long_w}/{short_w} at {f:g}x")
            alerts.append(
                {
                    "alert": f"LLM{name.title()}BurnRate{severity.title()}{suffix}",
                    "expr": " or ".join(clauses),
                    "for": cfg[f"{severity}_for"],
                    "labels": {"severity": severity, **labels},
                    "annotations": {
                        "summary": (
                            f"{'[DEMO] ' if demo else ''}{name} SLO ({objective:.0%}) is burning "
                            f'error budget at {{{{ $value | printf "%.1f" }}}}x'
                        ),
                        "description": (
                            f"Windows {' or '.join(pairs)} ({mode} windows). "
                            f"{slo['description'].strip()}"
                        ),
                        "runbook": "docs/framework.md",
                    },
                }
            )

    # Cost: budget signal, ticket only.
    cost = spec["cost"]
    cw = cfg["cost_window"]
    budget_1k = cost["budget_per_1k_requests"]
    recording.append(
        {
            "record": f"{p}:cost_per_1k_requests:rate{cw}",
            "expr": (
                f"1000 * sum by (llm_slo_cost_model) (rate(llm_slo_request_cost_sum[{cw}])) "
                f"/ sum by (llm_slo_cost_model) (rate(llm_slo_request_cost_count[{cw}]))"
            ),
            "labels": common_labels,
        }
    )
    alerts.append(
        {
            "alert": f"LLMCostBudgetExceeded{suffix}",
            "expr": (
                f'{p}:cost_per_1k_requests:rate{cw}{{llm_slo_cost_model="{cost["cost_model"]}"}} '
                f"> {budget_1k:g}"
            ),
            "for": cfg["cost_for"],
            "labels": {"severity": "ticket", "sli": "cost", **common_labels},
            "annotations": {
                "summary": (
                    f"{'[DEMO] ' if demo else ''}cost per 1k requests is "
                    f'{{{{ $value | printf "%.2f" }}}} USD, budget {budget_1k:g} '
                    f"({cost['cost_model']} model; assumptions, not real prices)"
                ),
                "runbook": "docs/framework.md",
            },
        }
    )

    groups = [
        {"name": f"llm-slo-{mode}.recording", "rules": recording},
        {"name": f"llm-slo-{mode}.alerts", "rules": alerts},
    ]
    if demo:
        for g in groups:
            g["interval"] = "15s"
    return groups


def render(obj: dict) -> str:
    return "---\n" + HEADER + yaml.safe_dump(obj, sort_keys=False, width=110, allow_unicode=True)


def main(check: bool = False) -> int:
    spec = yaml.safe_load((HERE / "slos.yaml").read_text(encoding="utf-8"))
    outputs = {}
    for mode, filename in (("prod", "rules.yaml"), ("demo", "rules-demo.yaml")):
        groups = build(spec, mode)
        outputs[HERE / "prometheus" / filename] = {"groups": groups}
        outputs[HERE / filename] = {
            "apiVersion": "monitoring.coreos.com/v1",
            "kind": "PrometheusRule",
            "metadata": {
                "name": "llm-slo-rules" if mode == "prod" else "llm-slo-rules-demo",
                "namespace": "llm",
                "labels": {"app": "llm-slo-lab", "slo_mode": mode},
            },
            "spec": {"groups": groups},
        }
    stale = []
    for path, obj in outputs.items():
        text = render(obj)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.relative_to(HERE.parent))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(HERE.parent)}")
    if stale:
        print("stale generated files (run `make slo-gen`):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
